[colors.primary]
background = '#0e131a'
foreground = '#fefefe'

[colors.selection]
text = '#fefefe'
background = '#23262e'

[colors.cursor]
text = '#0e131a'
cursor = '#1a9fff'

[colors.normal]
black   = '#0e131a'
red     = '#ff0451'
green   = '#19ff36'
yellow  = '#fff003'
blue    = '#008cf2'
magenta = '#004476'
cyan    = '#1a9fff'
white   = '#e3f3ff'

[colors.bright]
black   = '#8f9ca5'
red     = '#ff5388'
green   = '#5eff72'
yellow  = '#fff55e'
blue    = '#3cadff'
magenta = '#5ebbff'
cyan    = '#97d3ff'
white   = '#f3faff'
