set -g mouse on
set -s set-clipboard on
set -g extended-keys on
set -g extended-keys-format csi-u

unbind -T copy-mode MouseDragEnd1Pane
unbind -T copy-mode-vi MouseDragEnd1Pane

bind-key -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "xclip -selection clipboard -in"
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-no-clear "xclip -selection clipboard -in"

bind-key S choose-tree -Zs
